services:
  # The Node.js API Gateway
  - type: web
    name: api-gateway
    env: node
    rootDir: backend/api-gateway
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: THREATEYE_SERVICE_URL
        fromService:
          type: web
          name: ml-threateye-service
          property: url # <-- ADD THIS LINE
      - key: GUARD_SERVICE_URL
        fromService:
          type: web
          name: ml-guard-service
          property: url # <-- ADD THIS LINE
      - key: MONGO_URI
        sync: false

  # The Python Guard Service
  - type: web
    name: ml-guard-service
    env: python
    rootDir: backend/ml-guard-service
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

  # The Python ThreatEye Service
  - type: web
    name: ml-threateye-service
    env: python
    rootDir: backend/ml-threateye-service
    plan: free
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "gunicorn app:app"